import type { ChallengeDefinition } from "./types.js"

export const leJustePoisson = {
  id: "le-juste-poisson",
  title: "Le juste poisson",
  shortTitle: "Le juste poisson",
  emoji: "⚖️",
  description: "Estimez le poids de trois créatures marines sans couler sous la pression.",
  rules: [
    "Chaque banc saisit une estimation en kilogrammes avant la fin des 20 secondes.",
    "Plus votre estimation est proche du poids correct, plus votre banc marque de points.",
    "À chaque manche, les quatre bancs peuvent gagner de 1 à 4 points selon leur classement.",
  ],
  introMusicYoutubeId: "UaRrDZWhtWA",
  scoring: {
    kind: "ranked-relative",
    maxPoints: 4,
  },
  rounds: [
    {
      id: "crevette-mante-paon",
      kind: "number",
      kicker: "Manche 1 · Petit mais vénère",
      question: "Quel poids maximal peut atteindre cette crevette-mante paon ?",
      durationSeconds: 20,
      imageUrl: "/totems/totem-13.jpg",
      unit: "kg",
      correctAnswer: 0.09,
      answerLabel: "0,09 kg — soit 90 grammes",
      fact: "Son coup est si rapide qu'il provoque une bulle de cavitation.",
      sourceUrl: "https://www.cousteau.org/species/peacock-mantis-shrimp/",
    },
    {
      id: "pieuvre-geante-pacifique",
      kind: "number",
      kicker: "Manche 2 · Huit bras à la pesée",
      question: "Combien pesait la plus grosse pieuvre géante du Pacifique enregistrée ?",
      durationSeconds: 20,
      imageUrl: "/totems/totem-11.jpg",
      unit: "kg",
      correctAnswer: 272,
      answerLabel: "272 kg",
      fact: "Ce record tentaculaire atteignait aussi environ neuf mètres d'envergure.",
      sourceUrl: "https://ocean.si.edu/ocean-life/invertebrates/revealing-largest-octopus",
    },
    {
      id: "baleine-bleue",
      kind: "number",
      kicker: "Manche 3 · Niveau poids lourd divin",
      question: "Quel poids maximal peut atteindre une baleine bleue de l'Antarctique ?",
      durationSeconds: 20,
      imageUrl: "/totems/totem-17.jpg",
      unit: "kg",
      correctAnswer: 150000,
      answerLabel: "Environ 150 000 kg — soit 150 tonnes",
      fact: "C'est le plus grand animal ayant jamais vécu sur Terre.",
      sourceUrl: "https://www.fisheries.noaa.gov/species/blue-whale",
    },
  ],
} satisfies ChallengeDefinition
