import type { ChallengeDefinition } from "./types.js"

export const leJustePoisson = {
  id: "le-juste-poisson",
  title: "Le juste poisson",
  shortTitle: "Le juste poisson",
  emoji: "⚖️",
  introImageUrl: "/game/Le juste poisson/le-juste-poisson.png",
  description: "Estimez le poids de cinq créatures marines sans couler sous la pression.",
  rules: [
    "Chaque joueur estime le juste poids du poisson ; le meilleur de chaque banc porte le score de son équipe.",
    "À chaque manche, les poissons et les quatre bancs peuvent gagner de 10 à 40 points selon leur classement.",
    "20 secondes par manche",
  ],
  introMusicYoutubeId: "UaRrDZWhtWA",
  scoring: {
    kind: "ranked-relative",
    maxPoints: 4,
  },
  rounds: [
    {
      id: "hippocampe",
      kind: "number",
      kicker: "Manche 1 · Poids plume des abysses",
      question: "Combien pèse en moyenne un hippocampe ?",
      durationSeconds: 20,
      imageUrl: "/poids-hippocampe.avif",
      unit: "kg",
      estimateRange: { min: 0.001, max: 0.05, step: 0.0005, displayUnit: "g" },
      correctAnswer: 0.0125,
      answerLabel: "Environ 12,5 grammes",
      fact: "L'hippocampe nage debout et, chez lui, c'est le mâle qui porte les petits.",
      sourceUrl: "https://www.unodc.org/documents/data-and-analysis/wildlife/2020/WWCR2_Methods_Annext.pdf",
    },
    {
      id: "crabe-araignee-japonais",
      kind: "number",
      kicker: "Manche 2 · Arachnophobie aquatique",
      question: "Quel poids maximal peut atteindre ce crabe-araignée japonais ?",
      durationSeconds: 20,
      imageUrl: "/poids-crabe-araignee.jpg",
      unit: "kg",
      estimateRange: { min: 1, max: 30, step: 0.5, displayUnit: "kg" },
      correctAnswer: 20,
      answerLabel: "Environ 20 kg",
      fact: "Ses pattes déployées peuvent couvrir près de quatre mètres.",
      sourceUrl: "https://www.georgiaaquarium.org/animal/japanese-spider-crab/",
    },
    {
      id: "poisson-lune-mole",
      kind: "number",
      kicker: "Manche 3 · Pleine lune sous-marine",
      question: "Combien pesait le poisson-lune le plus lourd jamais mesuré ?",
      durationSeconds: 20,
      imageUrl: "/poids-moon-fish.jpg",
      unit: "kg",
      estimateRange: { min: 100, max: 3_000, step: 10, displayUnit: "kg" },
      correctAnswer: 2_744,
      answerLabel: "2 744 kg — soit près de 2,7 tonnes",
      fact: "Ce Mola alexandrini de 3,25 mètres, découvert près de l'île de Faial aux Açores, détient le record du plus lourd poisson osseux jamais mesuré.",
      sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/36218082/",
    },
    {
      id: "tortue-luth",
      kind: "number",
      kicker: "Manche 4 · Carapace catégorie poids lourd",
      question: "Quel poids maximal peut atteindre cette tortue luth ?",
      durationSeconds: 20,
      imageUrl: "/poids-tortue-luth.jpg",
      unit: "kg",
      estimateRange: { min: 100, max: 1_200, step: 10, displayUnit: "kg" },
      correctAnswer: 900,
      answerLabel: "Environ 900 kg",
      fact: "C'est la plus grande tortue du monde et sa carapace ressemble à du cuir.",
      sourceUrl: "https://www.fisheries.noaa.gov/s3/2023-09/Sea-Turtle-Framework-for-ESA-Sections-7.pdf",
    },
    {
      id: "baleine-bleue",
      kind: "number",
      kicker: "Manche 5 · Boss final titanesque",
      question: "Quel poids maximal peut atteindre une baleine bleue ?",
      durationSeconds: 20,
      imageUrl: "/poids-blue-whale.webp",
      unit: "kg",
      estimateRange: { min: 50_000, max: 250_000, step: 5_000, displayUnit: "t" },
      correctAnswer: 150000,
      answerLabel: "Environ 150 000 kg — soit 150 tonnes",
      fact: "C'est le plus grand animal ayant jamais vécu sur Terre.",
      sourceUrl: "https://www.fisheries.noaa.gov/species/blue-whale?page=1",
    },
  ],
} satisfies ChallengeDefinition
