import type { ChallengeDefinition } from "./types.js"

export const questionPourUnPoisson = {
  id: "question-pour-un-poisson",
  title: "Question pour un poisson",
  shortTitle: "Question pour un poisson",
  emoji: "🐠",
  description: "Dix plongées dans la culture marine, sans bouée ni question facile.",
  rules: [
    "Chaque poisson choisit sa propre réponse parmi quatre.",
    "Vous avez 20 secondes par question.",
    "Une bonne réponse rapporte 20 points au joueur ; son banc marque une seule fois si au moins un membre trouve.",
  ],
  introMusicYoutubeId: "Zcl98Bguq7k",
  scoring: { kind: "exact", points: 2 },
  rounds: [
    {
      id: "trois-coeurs",
      kicker: "Question 1 · Anatomie tentaculaire",
      question: "Combien de cœurs font circuler le sang d’un poulpe ?",
      durationSeconds: 20,
      kind: "choice",
      choices: [
        { id: "un", label: "Un" },
        { id: "deux", label: "Deux" },
        { id: "trois", label: "Trois" },
        { id: "neuf", label: "Neuf, un par cerveau" },
      ],
      correctAnswer: "trois",
      answerLabel: "Trois cœurs",
      fact: "Deux cœurs alimentent les branchies ; le troisième envoie le sang oxygéné dans le reste du corps.",
      sourceUrl: "https://ocean.si.edu/ocean-life/invertebrates/octopuses-squids-and-relatives",
    },
    {
      id: "dent-narval",
      kicker: "Question 2 · Dentiste des abysses",
      question: "La fameuse « corne » du narval mâle est en réalité…",
      durationSeconds: 20,
      kind: "choice",
      choices: [
        { id: "dent", label: "Une dent qui traverse la lèvre" },
        { id: "os", label: "Un os du crâne torsadé" },
        { id: "corne", label: "Une corne en kératine" },
        { id: "cartilage", label: "Une nageoire rigidifiée" },
      ],
      correctAnswer: "dent",
      answerLabel: "Une dent qui traverse la lèvre",
      fact: "C’est généralement la dent supérieure gauche, spiralée, qui pousse jusqu’à environ trois mètres.",
      sourceUrl: "https://oceanexplorer.noaa.gov/ocean-fact/narwhal/",
    },
    {
      id: "papa-enceint",
      kicker: "Question 3 · Maternité inversée",
      question: "Chez quel duo marin le mâle tombe-t-il enceint et met-il les petits au monde ?",
      durationSeconds: 20,
      kind: "choice",
      choices: [
        { id: "hippocampe", label: "Hippocampes et dragons de mer" },
        { id: "poisson-clown", label: "Poissons-clowns et demoiselles" },
        { id: "requin", label: "Requins-marteaux et raies" },
        { id: "manchot", label: "Manchots et macareux" },
      ],
      correctAnswer: "hippocampe",
      answerLabel: "Hippocampes et dragons de mer",
      fact: "La femelle dépose ses œufs dans la poche incubatrice du mâle, où ils sont fécondés puis portés.",
      sourceUrl: "https://oceanservice.noaa.gov/facts/seahorse.html",
    },
    {
      id: "concombre-evisceration",
      kicker: "Question 4 · Sortie de secours",
      question: "Que peut sacrifier un concombre de mer attaqué pour distraire son prédateur ?",
      durationSeconds: 20,
      kind: "choice",
      choices: [
        { id: "organes", label: "Une partie de ses organes internes" },
        { id: "peau", label: "Toute sa peau" },
        { id: "dents", label: "Ses dents empoisonnées" },
        { id: "cerveau", label: "Son deuxième cerveau" },
      ],
      correctAnswer: "organes",
      answerLabel: "Une partie de ses organes internes",
      fact: "Cette éviscération peut engluer l’assaillant ; le concombre de mer régénère ensuite les organes perdus.",
      sourceUrl: "https://www.montereybayaquarium.org/animals-the-ocean/animals-a-to-z/johnsons-sea-cucumber",
    },
    {
      id: "poisson-sang-chaud",
      kicker: "Question 5 · Bouillotte à nageoires",
      question: "Quel poisson est le seul connu à maintenir tout son corps plus chaud que l’eau ambiante ?",
      durationSeconds: 20,
      kind: "choice",
      choices: [
        { id: "thon", label: "Le thon rouge" },
        { id: "requin-blanc", label: "Le grand requin blanc" },
        { id: "espadon", label: "L’espadon" },
        { id: "opah", label: "L’opah, ou poisson-lune" },
      ],
      correctAnswer: "opah",
      answerLabel: "L’opah, ou poisson-lune",
      fact: "Ses nageoires pectorales produisent de la chaleur et ses branchies limitent sa perte grâce à des échangeurs vasculaires.",
      sourceUrl: "https://oceanservice.noaa.gov/facts/cold-blooded.html",
    },
    {
      id: "yeux-barreleye",
      kicker: "Question 6 · Pare-brise cérébral",
      question: "Que peuvent faire les yeux tubulaires du poisson revenant Macropinna dans sa tête transparente ?",
      durationSeconds: 20,
      kind: "choice",
      choices: [
        { id: "changer-couleur", label: "Changer de couleur pour hypnotiser" },
        { id: "sortir", label: "Sortir du crâne comme des périscopes" },
        { id: "tourner", label: "Pivoter vers le haut ou vers l’avant" },
        { id: "separer", label: "Regarder dans deux directions opposées" },
      ],
      correctAnswer: "tourner",
      answerLabel: "Pivoter vers le haut ou vers l’avant",
      fact: "Ses yeux verts pivotent dans un bouclier rempli de liquide pour repérer puis viser ses proies.",
      sourceUrl: "https://www.mbari.org/news/researchers-solve-mystery-of-deep-sea-fish-with-tubular-eyes-and-transparent-head/",
    },
    {
      id: "age-requin-groenland",
      kicker: "Question 7 · Retraite arctique",
      question: "Quel âge central les chercheurs ont-ils estimé pour le plus grand requin du Groenland étudié ?",
      durationSeconds: 20,
      kind: "choice",
      choices: [
        { id: "92", label: "92 ans" },
        { id: "192", label: "192 ans" },
        { id: "292", label: "292 ans" },
        { id: "392", label: "392 ans" },
      ],
      correctAnswer: "392",
      answerLabel: "392 ans, avec une marge de ± 120 ans",
      fact: "Daté au carbone 14 dans le cristallin, ce requin confirme la plus grande longévité connue chez un vertébré.",
      sourceUrl: "https://researchprofiles.ku.dk/en/publications/eye-lens-radiocarbon-reveals-centuries-of-longevity-in-the-greenl/",
    },
    {
      id: "estomac-etoile",
      kicker: "Question 8 · Bon appétit dehors",
      question: "Comment une étoile de mer commence-t-elle à digérer une proie trop grosse pour sa bouche ?",
      durationSeconds: 20,
      kind: "choice",
      choices: [
        { id: "acide", label: "Elle projette de l’acide" },
        { id: "estomac", label: "Elle sort son estomac du corps" },
        { id: "bras", label: "Elle détache un bras digestif" },
        { id: "bacteries", label: "Elle cultive des bactéries dessus" },
      ],
      correctAnswer: "estomac",
      answerLabel: "Elle sort son estomac du corps",
      fact: "Son estomac cardiaque digère les tissus à l’extérieur avant que le repas liquéfié ne soit absorbé.",
      sourceUrl: "https://ocean.si.edu/ocean-life/invertebrates/sea-stars-urchins-and-relatives",
    },
    {
      id: "meduse-immortelle",
      kicker: "Question 9 · Ctrl + Z biologique",
      question: "Quel tour de passe-passe permet à Turritopsis dohrnii d’être dite « méduse immortelle » ?",
      durationSeconds: 20,
      kind: "choice",
      choices: [
        { id: "clonage", label: "Elle fabrique un clone puis meurt" },
        { id: "hibernation", label: "Elle hiberne pendant des siècles" },
        { id: "polype", label: "Elle redevient un polype juvénile" },
        { id: "fusion", label: "Elle fusionne avec une autre méduse" },
      ],
      correctAnswer: "polype",
      answerLabel: "Elle redevient un polype juvénile",
      fact: "En cas de stress, ses cellules se reprogramment et elle remonte son cycle de vie de méduse adulte à polype.",
      sourceUrl: "https://www.nhm.ac.uk/discover/immortal-jellyfish-secret-to-cheating-death.html",
    },
    {
      id: "pyjama-poisson-perroquet",
      kicker: "Question 10 · Pyjama visqueux",
      question: "Dans quoi certains poissons-perroquets s’enveloppent-ils pour dormir ?",
      durationSeconds: 20,
      kind: "choice",
      choices: [
        { id: "sable", label: "Une boule de sable mâché" },
        { id: "algues", label: "Une couverture d’algues" },
        { id: "mucus", label: "Un cocon de mucus" },
        { id: "bulles", label: "Une bulle d’air" },
      ],
      correctAnswer: "mucus",
      answerLabel: "Un cocon de mucus",
      fact: "Cette enveloppe gluante les protège notamment de parasites suceurs de sang pendant leur sommeil.",
      sourceUrl: "https://ocean.si.edu/ocean-life/fish/parrotfish-mucus-cocoon",
    },
  ],
} satisfies ChallengeDefinition
