import type { ChallengeDefinition } from "./types.js"

export const quiVeutGagnerDesPoissons = {
  id: "qui-veut-gagner-des-poissons",
  title: "Qui veut gagner des poissons ?",
  shortTitle: "Qui veut gagner des poissons ?",
  emoji: "🐡",
  introImageUrl: "/game/Qui veut gagner des poissons/qui-veut-gagner-des-poissons.png",
  description:
    "Cinq questions, quatre réponses et un présentateur beaucoup trop sûr de ses branchies.",
  rules: [
    "Chaque poisson choisit A, B, C ou D avant la fin des 30 secondes.",
    "Chaque banc possède un unique joker 50/50 pour éliminer deux mauvaises réponses.",
    "Validez avec « C’est mon dernier mot » : les poissons ne font pas marche arrière.",
    "Les gains individuels montent à chaque bonne réponse, de 10 à 100 points ; un banc n'est crédité qu'une fois.",
  ],
  introMusicYoutubeId: "ntFaUwJMhg0",
  answeringMusicYoutubeId: "236sJVHRh1M",
  timerEndSoundYoutubeId: "5ijevRmcIBM",
  confirmationLabel: "C’est mon dernier mot",
  scoring: {
    kind: "escalating",
    points: [1, 2, 3, 5, 10],
  },
  rounds: [
    {
      id: "million-1-plus-grand-poisson",
      kind: "choice",
      kicker: "Palier 1 · 10 poissons",
      question: "Quel est le plus grand poisson vivant au monde ?",
      durationSeconds: 30,
      choices: [
        { id: "requin-baleine", label: "Le requin-baleine" },
        { id: "baleine-bleue", label: "La baleine bleue" },
        { id: "requin-blanc", label: "Le grand requin blanc" },
        { id: "thon-rouge", label: "Le thon rouge" },
      ],
      correctAnswer: "requin-baleine",
      answerLabel: "Le requin-baleine",
      fact: "Le requin-baleine est bien un requin, et le plus grand poisson vivant.",
      sourceUrl:
        "https://www.fisheries.noaa.gov/national/outreach-and-education/fun-facts-about-fascinating-fish",
    },
    {
      id: "million-2-coeurs-pieuvre",
      kind: "choice",
      kicker: "Palier 2 · 20 poissons",
      question: "Combien de cœurs fait battre une pieuvre ?",
      durationSeconds: 30,
      choices: [
        { id: "un", label: "Un" },
        { id: "deux", label: "Deux" },
        { id: "trois", label: "Trois" },
        { id: "huit", label: "Huit, un par bras" },
      ],
      correctAnswer: "trois",
      answerLabel: "Trois",
      fact: "Deux cœurs alimentent les branchies ; le troisième irrigue le reste du corps.",
      sourceUrl:
        "https://ocean.si.edu/ocean-life/invertebrates/octopuses-squids-and-relatives",
    },
    {
      id: "million-3-defense-narval",
      kind: "choice",
      kicker: "Palier 3 · 30 poissons",
      question: "La célèbre défense torsadée du narval est en réalité…",
      durationSeconds: 30,
      choices: [
        { id: "corne", label: "Une corne" },
        { id: "dent", label: "Une dent" },
        { id: "os-nasal", label: "Un os nasal" },
        { id: "nageoire", label: "Une nageoire rigidifiée" },
      ],
      correctAnswer: "dent",
      answerLabel: "Une dent",
      fact: "Cette défense est une canine géante qui traverse la lèvre supérieure du narval.",
      sourceUrl: "https://www.si.edu/stories/understanding-narwhals-smile",
    },
    {
      id: "million-4-epines-oursin",
      kind: "choice",
      kicker: "Palier 4 · 50 poissons",
      question: "Chez l’oursin comestible européen, combien d’épines peut-on compter au minimum ?",
      durationSeconds: 30,
      choices: [
        { id: "environ-3000", label: "Environ 3 000" },
        { id: "environ-5000", label: "Environ 5 000" },
        { id: "environ-8000", label: "Environ 8 000" },
        { id: "environ-10000", label: "Environ 10 000" },
      ],
      correctAnswer: "environ-3000",
      answerLabel: "Environ 3 000",
      fact: "Le nombre varie selon l’espèce et la taille ; pour l’oursin comestible européen, la référence utilisée indique au moins 3 000 épines.",
      sourceUrl: "https://www.gutenberg.org/files/47626/47626-h/47626-h.htm",
    },
    {
      id: "million-5-langue-baleine-bleue",
      kind: "choice",
      kicker: "Palier 5 · 100 poissons",
      question: "Combien pèse environ la langue d’une baleine bleue ?",
      durationSeconds: 30,
      choices: [
        { id: "12-kg", label: "12 kg" },
        { id: "51-kg", label: "51 kg" },
        { id: "120-kg", label: "120 kg" },
        { id: "2-7-tonnes", label: "2,7 tonnes" },
      ],
      correctAnswer: "2-7-tonnes",
      answerLabel: "2,7 tonnes",
      fact: "La langue d’une baleine bleue pèse environ 2,7 tonnes, soit à peu près le poids d’un éléphant.",
      sourceUrl: "https://nammco.no/blue-whale/",
    },
  ],
} as const satisfies ChallengeDefinition
