import type { ChallengeDefinition } from "./types.js"

const ASSET_ROOT = "/game/Who's that salmon"

export const whosDatSalmon = {
  id: "whos-dat-salmon",
  title: "Who's that salmon ?",
  shortTitle: "Who's that salmon ?",
  emoji: "🐟",
  introImageUrl: `${ASSET_ROOT}/whos-that-salmon-template.png`,
  description: "Quatre silhouettes impossibles, deux réponses et aucune excuse pour couler.",
  rules: [
    "Chaque joueur choisit A ou B avant la révélation de Poséithon.",
    "Chaque bonne réponse rapporte 20 points au joueur et 20 points à son banc.",
    "Le maître du jeu révèle la créature puis déclenche l'image suivante.",
  ],
  introMusicYoutubeId: "FsvGm4pqlW8",
  introMusicStartSeconds: 0,
  introMusicEndSeconds: 5,
  answeringMusicYoutubeId: "3pPR6IOV7Rg",
  scoring: { kind: "exact", points: 2 },
  rounds: [
    {
      id: "salmon-1-pikachu-baleine",
      kind: "choice",
      kicker: "Duel 1 · Foudre dans les abysses",
      question: "Qui se cache derrière cette silhouette ?",
      durationSeconds: 20,
      imageUrl: `${ASSET_ROOT}/1-guess-whale.png`,
      revealImageUrl: `${ASSET_ROOT}/1-reveal-whale.png`,
      choices: [
        { id: "baleine", label: "Baleine" },
        { id: "pikachu", label: "Pikachu" },
      ],
      correctAnswer: "pikachu",
      answerLabel: "Pikachu",
      fact: "Ce spécimen électrique a manifestement confondu une Poké Ball avec un bathyscaphe.",
      sourceUrl: "https://www.pokemon.com/fr/pokedex/pikachu",
    },
    {
      id: "salmon-2-crevette-mante",
      kind: "choice",
      kicker: "Duel 2 · Uppercut sous-marin",
      question: "Qui se cache derrière cette silhouette ?",
      durationSeconds: 20,
      imageUrl: `${ASSET_ROOT}/2-guess-mantis-shrimp.png`,
      revealImageUrl: `${ASSET_ROOT}/2-reveal-mantis-shrimp.png`,
      choices: [
        { id: "crevette-mante", label: "Crevette Mante" },
        { id: "langouste-mitraillette", label: "Langouste Mitraillette" },
      ],
      correctAnswer: "crevette-mante",
      answerLabel: "Crevette Mante",
      fact: "Son coup est si rapide qu'il crée une bulle de cavitation et une seconde onde de choc.",
      sourceUrl: "https://ocean.si.edu/ocean-life/invertebrates/mantis-shrimp",
    },
    {
      id: "salmon-3-saumon",
      kind: "choice",
      kicker: "Duel 3 · Retour aux sources",
      question: "Qui se cache derrière cette silhouette ?",
      durationSeconds: 20,
      imageUrl: `${ASSET_ROOT}/3-guess-salmon.png`,
      revealImageUrl: `${ASSET_ROOT}/3-reveal-salmon.png`,
      choices: [
        { id: "saumon", label: "Saumon" },
        { id: "carpe", label: "Carpe" },
      ],
      correctAnswer: "saumon",
      answerLabel: "Saumon",
      fact: "Le saumon retrouve sa rivière natale grâce à une mémoire olfactive redoutablement précise.",
      sourceUrl: "https://www.fisheries.noaa.gov/species/atlantic-salmon",
    },
    {
      id: "salmon-4-tortue-de-mer",
      kind: "choice",
      kicker: "Duel 4 · Carapace électrique",
      question: "Qui se cache derrière cette silhouette ?",
      durationSeconds: 20,
      imageUrl: `${ASSET_ROOT}/4-guess-pikachu.jpeg`,
      revealImageUrl: `${ASSET_ROOT}/4-reveal-pikachu.png`,
      choices: [
        { id: "pikachu", label: "Pikachu" },
        { id: "tortue-de-mer", label: "Tortue de mer" },
      ],
      correctAnswer: "tortue-de-mer",
      answerLabel: "Tortue de mer",
      fact: "Les tortues marines utilisent le champ magnétique terrestre comme une carte pour traverser les océans.",
      sourceUrl: "https://www.fisheries.noaa.gov/species/green-turtle",
    },
  ],
} as const satisfies ChallengeDefinition
