import type { ChallengeDefinition } from "./types.js"

export const whosDatSalmon = {
  id: "whos-dat-salmon",
  title: "Who’s Dat Salmon?",
  shortTitle: "Who’s Dat Salmon?",
  emoji: "🐟",
  description:
    "Reconnaissez cinq créatures marines cachées derrière leur silhouette.",
  rules: [
    "Une silhouette apparaît pendant 20 secondes.",
    "Chaque équipe choisit une réponse parmi quatre.",
    "Chaque bonne réponse rapporte 2 points.",
  ],
  introMusicYoutubeId: "UaRrDZWhtWA",
  scoring: { kind: "exact", points: 2 },
  rounds: [
    {
      id: "salmon-1-raie-manta",
      kind: "choice",
      kicker: "Ombre 1 · Vol sous-marin",
      question: "Qui se cache derrière cette silhouette ?",
      durationSeconds: 20,
      imageUrl: "/totems/totem-14.jpg",
      maskImage: true,
      choices: [
        { id: "raie-manta", label: "La raie manta" },
        { id: "requin-baleine", label: "Le requin-baleine" },
        { id: "pieuvre", label: "La pieuvre" },
        { id: "poisson-vache", label: "Le poisson-vache" },
      ],
      correctAnswer: "raie-manta",
      answerLabel: "La raie manta",
      fact: "Les taches sous le ventre d’une raie manta sont uniques et permettent de reconnaître chaque individu.",
      sourceUrl: "https://www.fisheries.noaa.gov/species/giant-manta-ray",
    },
    {
      id: "salmon-2-tortue-marine",
      kind: "choice",
      kicker: "Ombre 2 · Carapace express",
      question: "Qui se cache derrière cette silhouette ?",
      durationSeconds: 20,
      imageUrl: "/totems/totem-15.jpg",
      maskImage: true,
      choices: [
        { id: "tortue-marine", label: "La tortue marine" },
        { id: "morse", label: "Le morse" },
        { id: "beluga", label: "Le béluga" },
        { id: "poisson-perroquet", label: "Le poisson-perroquet" },
      ],
      correctAnswer: "tortue-marine",
      answerLabel: "La tortue marine",
      fact: "La tortue verte est la seule tortue marine adulte dont le régime est principalement herbivore.",
      sourceUrl: "https://www.fisheries.noaa.gov/species/green-turtle",
    },
    {
      id: "salmon-3-requin-baleine",
      kind: "choice",
      kicker: "Ombre 3 · Géant à pois",
      question: "Qui se cache derrière cette silhouette ?",
      durationSeconds: 20,
      imageUrl: "/totems/totem-16.jpg",
      maskImage: true,
      choices: [
        { id: "requin-baleine", label: "Le requin-baleine" },
        { id: "baleine-bleue", label: "La baleine bleue" },
        { id: "orque", label: "L’orque" },
        { id: "thon", label: "Le thon" },
      ],
      correctAnswer: "requin-baleine",
      answerLabel: "Le requin-baleine",
      fact: "Malgré son nom de baleine, c’est un requin — et le plus grand poisson de tout l’océan.",
      sourceUrl: "https://www.fisheries.noaa.gov/feature-story/year-life-larry-whale-shark",
    },
    {
      id: "salmon-4-baleine-bleue",
      kind: "choice",
      kicker: "Ombre 4 · Format XXL",
      question: "Qui se cache derrière cette silhouette ?",
      durationSeconds: 20,
      imageUrl: "/totems/totem-17.jpg",
      maskImage: true,
      choices: [
        { id: "baleine-bleue", label: "La baleine bleue" },
        { id: "beluga", label: "Le béluga" },
        { id: "requin-baleine", label: "Le requin-baleine" },
        { id: "orque", label: "L’orque" },
      ],
      correctAnswer: "baleine-bleue",
      answerLabel: "La baleine bleue",
      fact: "La baleine bleue est le plus grand animal ayant vécu sur Terre et peut engloutir plusieurs tonnes de krill par jour.",
      sourceUrl: "https://www.fisheries.noaa.gov/species/blue-whale",
    },
    {
      id: "salmon-5-orque",
      kind: "choice",
      kicker: "Ombre 5 · Costume noir et blanc",
      question: "Qui se cache derrière cette silhouette ?",
      durationSeconds: 20,
      imageUrl: "/totems/totem-18.jpg",
      maskImage: true,
      choices: [
        { id: "orque", label: "L’orque" },
        { id: "baleine-bleue", label: "La baleine bleue" },
        { id: "beluga", label: "Le béluga" },
        { id: "raie-manta", label: "La raie manta" },
      ],
      correctAnswer: "orque",
      answerLabel: "L’orque",
      fact: "L’orque est le plus grand membre de la famille des dauphins et vit dans des groupes sociaux complexes.",
      sourceUrl: "https://www.fisheries.noaa.gov/species/killer-whale",
    },
  ],
} as const satisfies ChallengeDefinition
