import { expect, test } from "@playwright/test"

test("four players form teams and start the tournament", async ({ browser }) => {
  const hostContext = await browser.newContext({ permissions: ["clipboard-read", "clipboard-write"] })
  const guestContexts = await Promise.all([browser.newContext(), browser.newContext(), browser.newContext()])
  const host = await hostContext.newPage()
  const guests = await Promise.all(guestContexts.map((context) => context.newPage()))

  await host.goto("/")
  await expect(host.locator('link[rel="icon"]')).toHaveAttribute("href", "/favicon.svg")
  await expect(host.getByText("🐡")).toBeVisible()
  await expect(host.getByText("L'AQUARIUM EN FOLIE")).toBeVisible()
  const brandTitle = host.getByText("Fish Tournament")
  await expect(brandTitle).toBeVisible()
  expect(await brandTitle.evaluate((element) => Number.parseFloat(getComputedStyle(element).fontSize))).toBeGreaterThan(20)
  const brandSubtitle = host.getByText("4 bancs de poissons vont s'affronter à travers quatre épreuves consécutives.")
  await expect(brandSubtitle).toBeVisible()
  expect(await brandSubtitle.evaluate((element) => Number.parseFloat(getComputedStyle(element).fontSize))).toBeGreaterThanOrEqual(14)
  const easterEgg = host.getByRole("link", { name: "Fish Party" })
  await expect(easterEgg).toHaveAttribute("href", "https://www.youtube.com/shorts/F3Rl8RRDq90")
  await expect(easterEgg).toHaveAttribute("target", "_blank")
  await expect(host.getByText("C'EST L'HEURE DU DUEL")).toBeVisible()
  const heroTitle = host.getByRole("heading", { name: "Quels poissons seront dignes de Poséithon ? 🔱" })
  await expect(heroTitle).toBeVisible()
  expect(await heroTitle.evaluate((element) => Number.parseFloat(getComputedStyle(element).fontSize))).toBeLessThan(48)
  expect(await heroTitle.evaluate((element) => {
    const range = document.createRange()
    range.selectNodeContents(element)
    return new Set([...range.getClientRects()].map((rect) => Math.round(rect.top))).size
  })).toBe(3)
  await expect(host.getByText("Merci de vous donner à fond marin et de ne pas crevette durant les épreuves. Les poissons victorieux seront récompensés d'une faveur divine.")).toBeVisible()
  await expect(host.locator("[data-testid='bubble-field'] > span")).toHaveCount(12)
  const musicPlayer = host.getByTestId("background-music-player")
  await expect(musicPlayer).toHaveAttribute("src", /youtube-nocookie\.com\/embed\/8g8Utx0gvv8/)
  await expect(host.getByRole("button", { name: "Activer la musique" })).toBeVisible()
  const demoButton = host.getByRole("button", { name: "Lancer la démo" })
  await expect(demoButton).toHaveCSS("color", "rgb(255, 255, 255)")
  await host.getByRole("button", { name: "Créer une partie" }).click()
  await expect(host.getByRole("button", { name: "Couper la musique" })).toBeVisible()
  await host.getByRole("button", { name: "Couper la musique" }).click()
  await expect(host.getByRole("button", { name: "Activer la musique" })).toBeVisible()
  await host.getByLabel("Nom de la partie").fill("L'aquarium du test")
  await host.getByLabel("Ton pseudo d'hôte").fill("Baptiste")
  await host.getByRole("button", { name: "Créer l'aquarium" }).click()

  await expect(host.getByText("En attente du banc")).toBeVisible()
  await expect(host.getByRole("button", { name: "Activer la musique", exact: true })).toBeVisible()
  expect(await host.evaluate(() => window.scrollY)).toBe(0)
  const code = await host.getByTestId("game-code").textContent()
  expect(code).toMatch(/^[A-Z2-9]{4}$/)
  await host.getByRole("button", { name: "Copier le code" }).click()
  expect(await host.evaluate(() => navigator.clipboard.readText())).toBe(code)

  await Promise.all(guests.map(async (guest, index) => {
    await guest.goto(`/?code=${code}`)
    await guest.getByRole("button", { name: "Rejoindre une partie" }).click()
    await guest.getByLabel("Ton pseudo").fill(["Léa", "Sam", "Jo"][index])
    await guest.getByRole("button", { name: "Plonger dans la partie" }).click()
  }))

  await expect(host.getByText("4 poissons à bord")).toBeVisible()
  await expect(host.getByRole("button", { name: "Lancer la partie" })).toBeDisabled()
  await Promise.all([
    host.getByRole("button", { name: "Scanner mon visage" }).click(),
    ...guests.map((guest) => guest.getByRole("button", { name: "Scanner mon visage" }).click()),
  ])
  await host.waitForTimeout(1_000)
  await expect(host.locator('[data-slot="avatar-image"]')).toHaveCount(0)
  await expect(host.getByText("Votre animal totem est…")).toBeVisible({ timeout: 8_000 })
  await Promise.all(guests.map((guest) => expect(guest.getByText("Votre animal totem est…")).toBeVisible({ timeout: 8_000 })))
  const totemImages = await Promise.all([host, ...guests].map((page) => page.getByTestId("totem-reveal-image").getAttribute("src")))
  expect(new Set(totemImages).size).toBe(4)
  await expect(host.getByRole("heading", { name: "Les 4 bancs" })).toBeVisible()
  await host.getByLabel("Nom de ton banc").fill("Les Moules Costaudes")
  await host.getByRole("button", { name: "Renommer mon banc" }).click()
  await expect(guests[0].getByText("Les Moules Costaudes")).toBeVisible()
  await expect(host.getByRole("button", { name: "Lancer la partie" })).toBeEnabled()
  await host.getByRole("button", { name: "Lancer la partie" }).click()

  await expect(host.getByRole("heading", { name: "Le juste poisson" })).toBeVisible()
  await expect(host.getByRole("button", { name: "Activer la musique", exact: true })).toBeVisible()
  await expect(host.getByTestId("challenge-music-player")).toHaveAttribute("src", /UaRrDZWhtWA/)
  await host.getByRole("button", { name: "Lancer l'épreuve" }).click()
  await host.getByLabel("Estimation en kg").fill("0,09")
  await host.getByRole("button", { name: "Valider la réponse" }).click()
  await expect(host.getByText("Réponse verrouillée")).toBeVisible()
  await host.getByRole("button", { name: "Révéler maintenant" }).click()
  await expect(host.getByText("0,09 kg — soit 90 grammes")).toBeVisible()
  await host.getByRole("button", { name: "Manche suivante" }).click()
  await host.getByLabel("Estimation en kg").fill("270")
  await host.getByRole("button", { name: "Valider la réponse" }).click()
  await host.getByRole("button", { name: "Révéler maintenant" }).click()
  await host.getByRole("button", { name: "Manche suivante" }).click()
  await host.getByLabel("Estimation en kg").fill("150000")
  await host.getByRole("button", { name: "Valider la réponse" }).click()
  await host.getByRole("button", { name: "Révéler maintenant" }).click()
  await host.getByRole("button", { name: "Voir le classement" }).click()
  await expect(host.getByRole("heading", { name: "Classement après l'épreuve 1" })).toBeVisible()
  await expect(host.getByRole("button", { name: "Activer la musique", exact: true })).toBeVisible()
  await host.getByRole("button", { name: "Découvrir l'épreuve suivante" }).click()
  await expect(host.getByRole("heading", { name: "Question pour un poisson" })).toBeVisible()
  await host.getByRole("button", { name: "Terminer le tournoi" }).click()
  await expect(host.getByTestId("final-suspense")).toBeVisible()
  await expect(host.getByTestId("final-suspense-player")).toHaveAttribute("src", /youtube-nocookie\.com\/embed\/wKw0pvc1HiE/)
  await expect(musicPlayer).toHaveAttribute("data-suspended", "true")
  await expect(host.getByRole("heading", { name: "Classement final" })).not.toBeVisible()
  await expect(host.getByRole("heading", { name: "Classement final" })).toBeVisible({ timeout: 10_000 })
  await expect(musicPlayer).toHaveAttribute("data-suspended", "false")
  await expect(host.getByRole("button", { name: "Activer la musique", exact: true })).toBeVisible()
  await expect(host.getByRole("img", { name: "Poséithon, dieu des océans" })).toBeVisible()
  await expect(host.getByTestId("final-confetti")).toBeVisible()
  await expect(guests[0].getByRole("heading", { name: "Classement final" })).toBeVisible({ timeout: 12_000 })

  await hostContext.close()
  await Promise.all(guestContexts.map((context) => context.close()))
})

test("demo launches a populated tournament directly", async ({ page }) => {
  await page.goto("/?demo=1")
  await expect(page.getByText("Aquarium actif")).toBeVisible()
  await expect(page.getByRole("heading", { name: "Le juste poisson" })).toBeVisible()
  await expect(page.getByText("Démo de Poséithon")).toBeVisible()
})
