import { expect, test } from "@playwright/test"

test("four players form teams, answer individually and start the tournament", async ({ browser }) => {
  test.setTimeout(90_000)
  const hostContext = await browser.newContext({ permissions: ["clipboard-read", "clipboard-write"] })
  const televisionContext = await browser.newContext({ viewport: { width: 1280, height: 720 } })
  const guestContexts = await Promise.all([browser.newContext(), browser.newContext(), browser.newContext(), browser.newContext()])
  const host = await hostContext.newPage()
  const guests = await Promise.all(guestContexts.map((context) => context.newPage()))

  await host.goto("/")
  await expect(host.locator('link[rel="icon"]')).toHaveAttribute("href", "/favicon.svg")
  await expect(host.getByText("🐡")).toBeVisible()
  await expect(host.getByText("L'AQUARIUM EN FOLIE")).toBeVisible()
  const brandTitle = host.getByText("Fish Tournament")
  await expect(brandTitle).toBeVisible()
  expect(await brandTitle.evaluate((element) => Number.parseFloat(getComputedStyle(element).fontSize))).toBeGreaterThan(20)
  const brandSubtitle = host.getByText("4 bancs de poissons s'affrontent à travers quatre épreuves consécutives légendaires.")
  await expect(brandSubtitle).toBeVisible()
  expect(await brandSubtitle.evaluate((element) => Number.parseFloat(getComputedStyle(element).fontSize))).toBeGreaterThanOrEqual(14)
  const easterEgg = host.getByRole("link", { name: "Fish Party" })
  await expect(easterEgg).toHaveAttribute("href", "https://www.youtube.com/shorts/F3Rl8RRDq90")
  await expect(easterEgg).toHaveAttribute("target", "_blank")
  await expect(host.getByText("C'EST L'HEURE DU DUEL")).toBeVisible()
  const heroTitle = host.getByRole("heading", { name: "Quels poissons seront dignes de Poséithon ? 🔱" })
  await expect(heroTitle).toBeVisible()
  expect(await heroTitle.evaluate((element) => Number.parseFloat(getComputedStyle(element).fontSize))).toBeLessThan(48)
  expect(await heroTitle.evaluate((element) => {
    const range = document.createRange()
    range.selectNodeContents(element)
    return new Set([...range.getClientRects()].map((rect) => Math.round(rect.top))).size
  })).toBe(3)
  await expect(host.getByText("Merci de vous donner à fond marin et de ne pas crevette durant les épreuves. Les poissons victorieux seront récompensés d'une faveur divine.")).toBeVisible()
  const footerEasterEgg = host.getByRole("link", { name: /Fabriqué dans les profondeurs/ })
  await expect(footerEasterEgg).toHaveAttribute("href", "/prank/footer.png")
  await expect(footerEasterEgg).toHaveAttribute("target", "_blank")
  await expect(host.locator("[data-testid='bubble-field'] > span")).toHaveCount(12)
  await expect(host.getByTestId("background-music-player")).toHaveCount(0)
  await expect(host.getByRole("button", { name: "Activer la musique" })).toHaveCount(0)
  const demoButton = host.getByRole("button", { name: "Lancer la démo" })
  await expect(demoButton).toHaveCSS("color", "rgb(255, 255, 255)")
  await host.getByRole("button", { name: "Créer une partie" }).click()
  await host.getByLabel("Nom de la partie").fill("L'aquarium du test")
  await host.getByLabel("Ton pseudo d'hôte").fill("Baptiste")
  await host.getByRole("button", { name: "Créer l'aquarium" }).click()

  await expect(host.getByText("En attente du banc")).toBeVisible()
  const musicPlayer = host.getByTestId("background-music-player")
  await expect(musicPlayer).toHaveAttribute("src", /youtube-nocookie\.com\/embed\/8g8Utx0gvv8/)
  await expect(host.getByText("Maître du jeu · hors compétition", { exact: true })).toBeVisible()
  await expect(host.getByRole("button", { name: "Scanner mon visage" })).toHaveCount(0)
  await expect(host.getByRole("button", { name: "Activer la musique", exact: true })).toBeVisible()
  expect(await host.evaluate(() => window.scrollY)).toBeLessThan(20)
  const code = await host.getByTestId("game-code").textContent()
  expect(code).toMatch(/^[A-Z2-9]{4}$/)
  await host.getByRole("button", { name: "Copier le code" }).click()
  expect(await host.evaluate(() => navigator.clipboard.readText())).toBe(code)

  const guestNames = ["Agathe", "Bastien", "Daniel", "Dimitri"]
  await Promise.all(guests.map(async (guest, index) => {
    await guest.goto(`/?code=${code}`)
    await guest.getByLabel("Qui es-tu ?").click()
    await guest.getByRole("option", { name: guestNames[index], exact: true }).click()
    await guest.getByRole("button", { name: "Plonger dans la partie" }).click()
    await expect(guest.getByTestId("background-music-player")).toHaveCount(0)
    await expect(guest.getByRole("button", { name: "Activer la musique" })).toHaveCount(0)
  }))

  await expect(host.getByText("4 poissons à bord")).toBeVisible()
  await expect(host.getByRole("button", { name: "Lancer la partie" })).toBeDisabled()
  await Promise.all(guests.map((guest) => guest.getByRole("button", { name: "Scanner mon visage" }).click()))
  await host.waitForTimeout(1_000)
  await expect(host.locator('[data-slot="avatar-image"]')).toHaveCount(0)
  await Promise.all(guests.map((guest) => expect(guest.getByText("Identité confirmée")).toBeVisible({ timeout: 25_000 })))
  const totemImages = await Promise.all(guests.map((page) => page.getByTestId("totem-reveal-image").getAttribute("src")))
  expect(new Set(totemImages).size).toBe(4)
  await expect(host.getByRole("heading", { name: "Les 4 bancs" })).toBeVisible()
  await expect(host.getByLabel("Nom de ton banc")).toHaveCount(0)
  await guests[0].getByLabel("Nom de ton banc").fill("Les Moules Costaudes")
  await guests[0].getByRole("button", { name: "Renommer mon banc" }).click()
  await expect(host.getByText("Les Moules Costaudes")).toBeVisible()
  await expect(host.getByRole("button", { name: "Lancer la partie" })).toBeEnabled()
  await host.getByRole("button", { name: "Lancer la partie" }).click()

  await expect(host.getByTestId("game-context-title")).toHaveText("Le juste poisson")
  await expect(host.locator("[data-music-control]")).toBeVisible()
  await expect(host.getByTestId("challenge-music-player")).toHaveAttribute("src", /UaRrDZWhtWA/)
  await expect(guests[0].getByTestId("challenge-music-player")).toHaveCount(0)
  await host.getByRole("button", { name: "Lancer l'épreuve" }).click()
  await expect(host.getByRole("slider", { name: "Estimation du poids" })).toHaveCount(0)
  await expect(host.getByTestId("answer-validation-sound-player")).toHaveCount(0)
  await expect(guests[0].getByTestId("answer-validation-sound-player")).toHaveAttribute("src", /sj_8f94zsUs/)
  const firstWeightSlider = guests[0].getByRole("slider", { name: "Estimation du poids" })
  await expect(firstWeightSlider).toBeVisible()
  await expect(guests[0].getByRole("button", { name: "Valider la réponse" })).toBeDisabled()
  await Promise.all(guests.map((guest) => guest.getByRole("slider", { name: "Estimation du poids" }).press("End")))
  await expect(guests[0].locator("output").getByText("1 000 g", { exact: true })).toBeVisible()
  await Promise.all(guests.map((guest) => guest.getByRole("button", { name: "Valider la réponse" }).click()))
  await expect(guests[0].getByText("Réponse verrouillée")).toBeVisible()
  await expect(guests[1].getByText("Réponse verrouillée")).toBeVisible()
  await host.getByRole("button", { name: "Révéler maintenant" }).click()
  await expect(host.getByText("Environ 12,5 grammes")).toBeVisible()
  await expect(host.getByLabel("+40 points").first()).toBeVisible()
  await host.getByRole("button", { name: "Manche suivante" }).click()
  const secondWeightSlider = guests[0].getByRole("slider", { name: "Estimation du poids" })
  await expect(secondWeightSlider).toBeVisible()
  await Promise.all(guests.map((guest) => guest.getByRole("slider", { name: "Estimation du poids" }).press("End")))
  await expect(guests[0].locator("output").getByText("100 kg", { exact: true })).toBeVisible()
  await Promise.all(guests.map((guest) => guest.getByRole("button", { name: "Valider la réponse" }).click()))
  await host.getByRole("button", { name: "Révéler maintenant" }).click()
  await host.getByRole("button", { name: "Manche suivante" }).click()
  const thirdWeightSlider = guests[0].getByRole("slider", { name: "Estimation du poids" })
  await expect(thirdWeightSlider).toBeVisible()
  await Promise.all(guests.map((guest) => guest.getByRole("slider", { name: "Estimation du poids" }).press("End")))
  await expect(guests[0].locator("output").getByText("3 000 kg", { exact: true })).toBeVisible()
  await Promise.all(guests.map((guest) => guest.getByRole("button", { name: "Valider la réponse" }).click()))
  await host.getByRole("button", { name: "Révéler maintenant" }).click()
  for (let round = 4; round <= 5; round += 1) {
    await host.getByRole("button", { name: "Manche suivante" }).click()
    await Promise.all(guests.map(async (guest) => {
      await guest.getByRole("slider", { name: "Estimation du poids" }).press("End")
      await guest.getByRole("button", { name: "Valider la réponse" }).click()
    }))
    await host.getByRole("button", { name: "Révéler maintenant" }).click()
  }
  await host.getByRole("button", { name: "Voir le classement" }).click()
  await expect(host.getByRole("heading", { name: "Classement après l'épreuve 1" })).toBeVisible()
  const playerRanking = host.getByRole("list", { name: "Classement individuel des joueurs" })
  await expect(playerRanking).toBeVisible()
  await expect(playerRanking.getByRole("listitem")).toHaveCount(4)
  for (const name of guestNames) {
    await expect(playerRanking.getByText(name, { exact: true })).toBeVisible()
  }
  await playerRanking.getByRole("button", { name: /Agrandir la photo de/ }).first().click()
  await expect(host.getByRole("dialog", { name: /Portrait de/ })).toBeVisible()
  await host.getByRole("button", { name: "Fermer le portrait" }).click()
  await expect(host.getByRole("dialog", { name: /Portrait de/ })).not.toBeVisible()
  const television = await televisionContext.newPage()
  await television.goto(`/tv/${code}`)
  await expect(television.getByRole("heading", { name: "La grille des poissons" })).toBeVisible()
  await expect(host.getByRole("button", { name: "Déchaîner la faveur" })).toBeVisible()
  await host.getByRole("button", { name: "Déchaîner la faveur" }).click()
  await expect(host.getByText("La faveur attend le geste de Agathe.")).toBeVisible()
  await expect(guests[0].getByRole("button", { name: "Déchaîner la roue" })).toBeVisible()
  await expect(guests[1].getByRole("button", { name: "Déchaîner la roue" })).toHaveCount(0)
  await expect(television.getByRole("heading", { name: "Agathe doit déchaîner la roue" })).toBeVisible()
  await expect(host.getByRole("button", { name: "Déchaîner la faveur" })).toHaveCount(0)
  await expect(host.getByRole("button", { name: "Découvrir l'épreuve suivante" })).toBeDisabled()
  await guests[0].getByRole("button", { name: "Déchaîner la roue" }).click()
  await expect(host.getByRole("heading", { name: "La roue fend les courants…" })).toBeVisible()
  await expect(television.getByRole("heading", { name: "La roue fend les courants…" })).toBeVisible()
  await expect(host.getByRole("heading", { name: "Sardine légendaire remportée" })).toBeVisible({ timeout: 10_000 })
  await expect(television.getByRole("heading", { name: "Sardine légendaire remportée" })).toBeVisible({ timeout: 10_000 })
  await expect(host.getByText("Agathe remporte la sardine légendaire !")).toBeVisible()
  await expect(host.getByRole("button", { name: "Découvrir l'épreuve suivante" })).toBeEnabled()
  await expect(host.locator("[data-music-control]")).toBeVisible()
  await host.getByRole("button", { name: "Découvrir l'épreuve suivante" }).click()
  await expect(host.getByTestId("game-context-title")).toHaveText("Question pour un poisson")
  await host.getByRole("button", { name: "Terminer le tournoi" }).click()
  await expect(host.getByTestId("final-suspense")).toBeVisible()
  const musicControl = host.locator("[data-music-control]")
  await expect(musicControl).toBeVisible()
  expect(await musicControl.evaluate((element) => Number.parseInt(getComputedStyle(element).zIndex, 10)))
    .toBeGreaterThan(await host.getByTestId("final-suspense").evaluate((element) => Number.parseInt(getComputedStyle(element).zIndex, 10)))
  await expect(host.getByTestId("final-suspense-player")).toHaveAttribute("src", /youtube-nocookie\.com\/embed\/wKw0pvc1HiE/)
  await expect(guests[0].getByTestId("final-suspense")).toBeVisible({ timeout: 4_000 })
  await expect(guests[0].getByTestId("final-suspense-player")).toHaveCount(0)
  await expect(musicPlayer).toHaveAttribute("data-suspended", "true")
  await expect(host.getByRole("heading", { name: "Classement final" })).not.toBeVisible()
  await expect(host.getByRole("heading", { name: "Classement final" })).toBeVisible({ timeout: 10_000 })
  await expect(host.getByTestId("final-suspense-player")).toHaveCount(1)
  await expect(musicPlayer).toHaveAttribute("data-suspended", "true")
  await expect(musicPlayer).toHaveAttribute("data-suspended", "false", { timeout: 6_000 })
  await expect(host.locator("[data-music-control]")).toBeVisible()
  await expect(host.getByRole("img", { name: "Poséithon, dieu des océans" })).toBeVisible()
  await expect(host.getByTestId("final-confetti")).toBeVisible()
  await host.getByRole("tab", { name: "Poissons" }).click()
  await expect(host.getByRole("list", { name: /Classement final des poissons/ })).toBeVisible()
  await expect(host.getByLabel("Champion individuel")).toBeVisible()
  await expect(host.getByLabel("Dernier du classement")).toBeVisible()
  await expect(guests[0].getByRole("dialog", { name: "Poséithon a un trésor pour toi" })).toBeVisible({ timeout: 12_000 })
  await guests[0].getByRole("button", { name: "Fermer" }).click()
  await expect(guests[0].getByRole("heading", { name: "Classement final" })).toBeVisible({ timeout: 12_000 })

  await hostContext.close()
  await televisionContext.close()
  await Promise.all(guestContexts.map((context) => context.close()))
})

test("demo launches a populated tournament directly", async ({ page }) => {
  await page.goto("/?demo=1")
  await expect(page.getByText("Aquarium actif")).toBeVisible()
  await expect(page.getByTestId("game-context-title")).toHaveText("Le juste poisson")
  await expect(page.getByText("Démo de Poséithon")).toHaveCount(0)

  const playerPopupPromise = page.waitForEvent("popup")
  await page.getByRole("button", { name: "Ouvrir la vue joueur" }).click()
  const player = await playerPopupPromise
  await expect(player.getByText("Aquarium actif")).toBeVisible()
  await expect(player.getByTestId("game-context-title")).toHaveText("Le juste poisson")

  const hostSession = await page.evaluate(() => {
    const session = JSON.parse(localStorage.getItem("fish-tournament-session") ?? "null") as { gameCode?: string } | null
    return session
  })
  const playerSession = await player.evaluate(() => {
    const session = JSON.parse(sessionStorage.getItem("fish-tournament-session") ?? "null") as { gameCode?: string; hostToken?: string } | null
    return session
  })
  const gameCode = hostSession?.gameCode
  expect(gameCode).toMatch(/^[A-Z2-9]{4}$/)
  expect(playerSession?.gameCode).toBe(gameCode)
  expect(playerSession?.hostToken).toBeUndefined()

  await page.getByRole("button", { name: "Lancer l'épreuve" }).click()
  const playerAnswer = player.getByRole("slider", { name: "Estimation du poids" })
  await expect(playerAnswer).toBeVisible()
  await playerAnswer.press("End")
  await player.getByRole("button", { name: "Valider la réponse" }).click()
  await expect(player.getByText("Réponse verrouillée")).toBeVisible()
  await expect(page.getByRole("button", { name: "Révéler maintenant" })).toBeVisible()

  await expect(page.getByRole("button", { name: "Terminer le tournoi", exact: true }).first()).toBeVisible()
  await player.close()
  const homeButton = page.getByRole("button", { name: "Accueil · nouvelle partie", exact: true })
  const homeButtonBox = await homeButton.boundingBox()
  const viewport = page.viewportSize()
  expect(homeButtonBox).not.toBeNull()
  expect(viewport).not.toBeNull()
  expect(homeButtonBox!.x).toBeGreaterThanOrEqual(0)
  expect(homeButtonBox!.x + homeButtonBox!.width).toBeLessThanOrEqual(viewport!.width)
  await homeButton.click()
  await expect(page.getByRole("heading", { name: "Quels poissons seront dignes de Poséithon ? 🔱" })).toBeVisible()

  const response = await page.request.get(`/api/games/${gameCode}`)
  expect(response.ok()).toBe(true)
  expect((await response.json()).status).toBe("finished")
})
